### ISSUE TITLE
Classes .col-xm and .col-xs-n don't exist

### ISSUE THREAD

**Issue by alexsc6955** [Rincorpes/vbtizer#2]
Something is hapend with the `make-grid-columns` mixin.

This doesn't add classes for the `xs` breakpoint.

**Comment by rincorpes** [comment]
Classes `.col-x` and `.col-xs-n` don't exist. instead use `.col` or `.col-n` is the default class for extra small.

Watching this I coul find the same issue #1 with `.offset-col` and I solved it. And besides i add a new mixin to max media breakpoints.
